version: "3"

services:
  # App
  app:
    container_name: rpi_server_app
    build: .
    restart: always
    ports:
      - ${SERVER_PORT}:5000
    depends_on:
      - db
    links:
      - db
    volumes:
      - .:/app

  # MariaDB
  db:
    image: mariadb:bionic
    container_name: rpi_server_db
    env_file: .env
    restart: always
    ports:
     - ${MYSQL_PORT}:3306
    volumes:
      - './mariadb_data:/data/mariadb'

  # PhpMyAdmin
  phpmyadmin:
    image: jackgruber/phpmyadmin:latest
    container_name: rpi_server_phpmyadmin
    restart: always
    env_file: .env
    depends_on:
      - db
    ports:
      - ${PMA_PORT}:80

volumes:
  mariadb:
    driver: local